Test: Add test for workflow Scheduler service
redhat-developer/parodos pull request #65
Opened 2023-02-22 12:30 UTC by eloycoto

2023-02-22 13:28 UTC, masayag commented on workflow-service/src/test/java/com/redhat/parodos/workflow/execution/scheduler/WorkFlowSchedulerServiceImplTest.java
> +	public void each_init() {
pls follow the method naming convention - https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names ;-)

2023-02-22 16:54 UTC, pkliczewski reviewed
/lgtm

2023-02-22 17:11 UTC, anludke requested changes

2023-02-22 17:11 UTC, anludke commented on workflow-service/src/test/java/com/redhat/parodos/workflow/execution/scheduler/WorkFlowSchedulerServiceImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
@eloycoto please use explicit import for each class

2023-02-23 13:43 UTC, anludke approved these changes

2023-02-23 13:43 UTC, merged