Test: WorkFlow-service ContinuationService
redhat-developer/parodos pull request #66
Opened 2023-02-22 16:47 UTC by eloycoto

2023-02-22 17:13 UTC, anludke requested changes

2023-02-22 17:13 UTC, anludke commented on workflow-service/src/test/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
@eloycoto please use explicit import for each class

2023-02-23 10:57 UTC, pkliczewski reviewed
Overall looks good. Only one small comment.

2023-02-23 10:57 UTC, pkliczewski commented on workflow-service/src/test/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceTest.java
> +	@Test
Why do we need this annotation here?

2023-02-23 12:31 UTC, eloycoto commented on workflow-service/src/test/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceTest.java
> +	@Test
intelj magic :sweat_smile:

2023-02-23 13:43 UTC, anludke approved these changes

2023-02-23 13:43 UTC, merged